import type { Metadata } from "next";
import Link from "next/link";
import { defaultOgImage } from "@/lib/seo/metadata";
import { breadcrumbJsonLd } from "@/lib/seo/json-ld";
import {
  Droplets,
  Mountain,
  Zap,
  Fish,
  Waves,
  TreePine,
  Clock,
  Landmark,
  Flame,
  Award,
  Lightbulb,
  Camera,
  Wine,
  Umbrella,
  MapPin,
  Ticket,
  Sun,
  Snowflake,
} from "lucide-react";

export const metadata: Metadata = {
  title: "The Complete Guide to Niagara Falls (2026)",
  description:
    "Everything you need to know about Niagara Falls — jaw-dropping facts, 12,500 years of history, legendary daredevils, hydroelectric power, insider travel tips, and the best tours to book.",
  openGraph: {
    title: "The Complete Guide to Niagara Falls | Explore Niagara",
    description:
      "Facts, history, daredevils, science, trivia, and travel tips — the definitive Niagara Falls resource.",
    images: [defaultOgImage],
  },
  alternates: {
    canonical: "https://explore-niagara.com/guide",
  },
};

const FACTS = [
  { icon: Droplets, title: "Massive Water Volume", text: "Over 168,000 cubic metres of water thunder over the crestline every single minute during peak hours — around 700,000 gallons per second." },
  { icon: Mountain, title: "Horseshoe Falls Dimensions", text: "The Canadian Horseshoe Falls drops an average of 57 metres (188 ft) and stretches approximately 790 metres (2,600 ft) wide — far larger than the American side." },
  { icon: Zap, title: "Hydroelectric Powerhouse", text: "Power plants on both sides produce nearly 4–5 million kilowatts of electricity — supplying over a quarter of all power used in New York State and Ontario." },
  { icon: Waves, title: "Erosion in Progress", text: "The falls erode roughly 30 cm (12 inches) per year — down from 90 cm historically thanks to engineering. At this rate, they'll reach Lake Erie in about 50,000 years." },
  { icon: Fish, title: "Fish Survive the Plunge", text: "Fish regularly go over Niagara Falls and almost all survive, thanks to their ability to flow naturally with the current. Some are briefly stunned but swim away." },
  { icon: TreePine, title: "The Green Colour", text: "That distinctive emerald-green hue comes from an estimated 60 tonnes of dissolved salts and extremely fine rock flour generated by the river's relentless erosion every minute." },
  { icon: Droplets, title: "Four Great Lakes Drain Here", text: "Water from Lakes Superior, Michigan, Huron, and Erie all drain through the Niagara River — representing nearly 1/5 of all Earth's fresh water." },
  { icon: Clock, title: "Night-Time Flow is Halved", text: "Under an international treaty, flow over the falls is reduced at night so more water can be diverted for hydroelectric generation — the spectacle is managed for both power and tourism." },
  { icon: Landmark, title: "America's Oldest State Park", text: "Niagara Falls State Park was established in 1885 and designed by Frederick Law Olmsted — the same landscape architect who designed Central Park in New York City." },
];

const TIMELINE = [
  { year: "~10,500 BC", title: "The Ice Age Gives Birth to Niagara", text: "As glaciers melted, vast quantities of meltwater carved through the Niagara Escarpment, creating the falls. Southern Ontario was covered in ice sheets 2–3 km thick." },
  { year: "~10,000 BC", title: "First Humans Arrive", text: "The Paleo-Indian Clovis people were among the first inhabitants — nomadic hunters who witnessed the very birth of the falls, living on tundra and hunting caribou, mastodons, and elk." },
  { year: "1615", title: "Étienne Brûlé — First European", text: "French explorer Étienne Brûlé is believed to have become the first European to see the falls. The Indigenous Iroquois name — Onguiaahra, meaning 'Thundering Waters' — appears on maps as early as 1641." },
  { year: "1678", title: "Father Hennepin's Discovery", text: "Recollet priest Louis Hennepin visited in December 1678 and published the first engraving of the falls in 1697. He was so awestruck he estimated their height at 183 metres — more than three times actual." },
  { year: "1812", title: "The War of 1812", text: "The Niagara River became a frontline. The region saw fierce battles, and artifacts are still found along the riverside. Niagara-on-the-Lake was taken by American forces and later burned." },
  { year: "1825", title: "Tourism Begins in Earnest", text: "The completion of the Erie Canal made Niagara Falls easily accessible for the first time. Within 50 years, tourism had increased tenfold to become the area's dominant industry." },
  { year: "1883", title: "America's First State Park", text: "The Niagara Reservation was created — the very first state park in the United States. An early triumph of the conservation movement against commercial exploitation of the falls." },
  { year: "1896", title: "The Birth of Hydroelectric Power", text: "Nikola Tesla and George Westinghouse developed the world's first large-scale hydroelectric power plant here. In November 1896, AC electricity was transmitted for the first time to Buffalo, NY — changing the world." },
  { year: "1969", title: "The Falls Are 'Turned Off'", text: "The U.S. Army Corps of Engineers built a temporary dam, completely stopping flow over the American Falls for months. Engineers studied the riverbed. Two bodies were discovered in the dried-out falls." },
  { year: "2012", title: "Nik Wallenda's Tightrope Walk", text: "Nik Wallenda became the first person to walk a tightrope directly over the thundering Niagara Falls from the US to Canada, drawing a global television audience of millions." },
];

const DAREDEVILS = [
  { year: "1829", name: "Sam Patch — The Jersey Jumper", text: "Constructed a platform 85 feet above the Niagara River and jumped in. He survived, returned days later to jump from 130 feet — and survived again. He became one of America's first celebrities." },
  { year: "1859", name: "Blondin — The Great Tightrope Walker", text: "Jean François Gravelet performed breathtaking tightrope walks across the Niagara Gorge during 1859–1860, thrilling tens of thousands. He even crossed blindfolded, on stilts, and pushing a wheelbarrow." },
  { year: "1901", name: "Annie Edson Taylor — First Barrel Rider", text: "On her 63rd birthday, schoolteacher Annie became the first person to go over the falls in a barrel and survive. Days before, her cat was sent over to test it — the cat also survived." },
  { year: "1911", name: "Bobby Leach — The Steel Barrel", text: "Survived in a crude steel barrel but spent six months in hospital with two broken kneecaps and a fractured jaw. Ironically, years later he died after slipping on an orange peel." },
  { year: "2003", name: "Kirk Jones — No Device Needed", text: "Became the first person to survive going over Horseshoe Falls without any flotation device — he just swam over. Jones was fined $2,300 and banned for life from entering Canada." },
  { year: "2012", name: "Nik Wallenda — The Wire Walk", text: "Seventh-generation member of the Flying Wallendas family walked a 550-metre tightrope directly over Horseshoe Falls from the US to Canada, watched live by millions worldwide." },
];

const TRIVIA = [
  { q: "It's NOT the world's tallest", text: "Around 500 waterfalls are taller. Venezuela's Angel Falls stands at 979 metres — nearly 17 times higher. But none match Niagara's combination of height and staggering volume." },
  { q: "Marilyn Monroe filmed here", text: "The 1953 film Niagara starring Marilyn Monroe was filmed in Niagara Falls, Ontario — cementing the falls' romantic and cinematic mystique worldwide." },
  { q: "P.T. Barnum wanted a circus here", text: "The legendary showman proposed turning Goat Island into a circus ground. The idea was rejected, preserving it for the public as part of Niagara Falls State Park." },
  { q: "A golf ball was hit across it", text: "In 2019, pro golfer Maurice Allen became the first person to hit a golf ball across Horseshoe Falls — a shot of 393 yards through the mist, landing on Goat Island." },
  { q: "It was 'turned off' in 1969", text: "The US Army Corps of Engineers literally stopped the water over the American Falls by building a temporary dam. Two bodies were found in the riverbed during the process." },
  { q: "Black squirrels crossed the bridge", text: "According to local legend, there were no black squirrels on the US side until the first suspension bridge was built — the squirrels crossed over from Canada, and you can still spot them today." },
  { q: "The Underground Railroad ran through here", text: "Niagara Falls was a crucial stop on the Underground Railroad. The historic Village of Lewiston was the last stop before freedom in Canada." },
  { q: "It doesn't actually freeze", text: "The water flows too fast to freeze. However, in 1848 an upstream ice jam reduced the flow to a trickle for several hours — the only time in recorded history." },
  { q: "1/5 of Earth's fresh water", text: "The water comes from four of the five Great Lakes, which together hold nearly one-fifth of all the fresh water on the entire planet." },
];

const TIPS = [
  { icon: Camera, title: "Canadian Side is Better", text: "The Canadian side offers the most dramatic views, especially of Horseshoe Falls. For the best vantage points, stay in Ontario." },
  { icon: Sun, title: "Visit at Night", text: "Every evening after dusk, the falls are illuminated in spectacular multi-coloured light. The illumination show is completely free to watch from the parkway." },
  { icon: Umbrella, title: "Go in June", text: "June offers the best balance of warm weather, fewer summer crowds, and boat tours operating at full schedule." },
  { icon: Wine, title: "Don't Skip Niagara-on-the-Lake", text: "Only 20 minutes away, it's one of Canada's most beautiful towns with nearly 100 wineries. Add a half-day — you won't regret it." },
  { icon: Droplets, title: "Bring a Poncho", text: "Both the boat cruise and Journey Behind the Falls will drench you. Ponchos are provided, but waterproof shoes are your responsibility!" },
  { icon: MapPin, title: "Free Shuttle in Season", text: "The free 'Discover Niagara' shuttle runs May–October, linking attractions and extending to Niagara-on-the-Lake. Avoid parking headaches." },
  { icon: Ticket, title: "Table Rock is Free", text: "You can view Horseshoe Falls for free from Table Rock Welcome Centre — no ticket required for the most dramatic ground-level view." },
  { icon: Snowflake, title: "Try Icewine", text: "The Niagara Peninsula is the world's leading Icewine producer. Try a tasting at any of the 100+ local wineries." },
];

export default function GuidePage() {
  return (
    <div>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(breadcrumbJsonLd([
            { name: "Home", url: "https://explore-niagara.com" },
            { name: "Guide", url: "https://explore-niagara.com/guide" },
          ])),
        }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Article",
            headline: "The Complete Guide to Niagara Falls",
            description: "Everything you need to know about Niagara Falls — facts, history, daredevils, science, and travel tips.",
            author: { "@type": "Organization", name: "Explore Niagara" },
            datePublished: "2026-03-01",
            dateModified: "2026-03-25",
            image: "https://explore-niagara.com/opengraph-image",
            publisher: { "@type": "Organization", name: "Explore Niagara", logo: { "@type": "ImageObject", url: "https://explore-niagara.com/logo.webp" } },
          }),
        }}
      />

      {/* Hero */}
      <section className="relative bg-gradient-to-br from-[#031c2e] via-[#064a6e] to-[#0a9bb5] py-24 md:py-36 text-center overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-0 left-1/4 w-1/2 h-full bg-gradient-to-b from-white/30 via-white/10 to-transparent blur-3xl" />
        </div>
        <div className="relative z-10 max-w-4xl mx-auto px-4">
          <span className="inline-block bg-amber-500 text-[#031c2e] text-xs font-bold uppercase tracking-widest px-4 py-1.5 rounded-full mb-6">
            World Wonder &middot; Canada & USA
          </span>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-white leading-tight mb-6">
            The Complete Guide to <span className="text-cyan-300">Niagara Falls</span>
          </h1>
          <p className="text-lg text-white/75 max-w-2xl mx-auto italic mb-10">
            The most powerful waterfall in North America — straddling two nations, shaping two centuries of history, and still thundering on.
          </p>
          <div className="flex flex-wrap justify-center gap-4 mb-10">
            {[
              { num: "168K", label: "m³/min flow" },
              { num: "57m", label: "Horseshoe drop" },
              { num: "12,500", label: "years old" },
              { num: "30M+", label: "visitors/year" },
            ].map((s) => (
              <div key={s.label} className="bg-white/10 backdrop-blur-sm border border-white/20 rounded-2xl px-5 py-3 text-center min-w-[100px]">
                <div className="text-2xl font-bold text-cyan-300">{s.num}</div>
                <div className="text-[10px] text-white/60 uppercase tracking-wider mt-1">{s.label}</div>
              </div>
            ))}
          </div>
          <Link
            href="/tours"
            className="inline-block bg-amber-500 text-[#031c2e] font-bold px-8 py-4 rounded-full hover:bg-amber-400 transition-colors shadow-lg"
          >
            Explore Tours
          </Link>
        </div>
      </section>

      {/* Quick Nav */}
      <nav className="bg-white border-b border-gray-100 sticky top-16 md:top-20 z-40">
        <div className="max-w-7xl mx-auto px-4 flex gap-6 overflow-x-auto py-3 text-sm" aria-label="Guide sections">
          {[
            { href: "#facts", label: "Facts" },
            { href: "#history", label: "History" },
            { href: "#daredevils", label: "Daredevils" },
            { href: "#power", label: "Science" },
            { href: "#trivia", label: "Trivia" },
            { href: "#tips", label: "Tips" },
          ].map((l) => (
            <a key={l.href} href={l.href} className="text-gray-500 hover:text-primary font-medium whitespace-nowrap transition-colors">
              {l.label}
            </a>
          ))}
        </div>
      </nav>

      {/* ─── FACTS ─── */}
      <section id="facts" className="py-16 md:py-24 scroll-mt-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <span className="text-xs font-bold uppercase tracking-widest text-primary mb-2 block">The Numbers</span>
          <h2 className="text-3xl md:text-4xl font-bold text-dark mb-3">Jaw-Dropping Facts</h2>
          <p className="text-gray-500 max-w-3xl mb-10 leading-relaxed">
            Niagara Falls is not the tallest waterfall on Earth — but nothing comes close to matching its sheer volume and accessibility. Here&apos;s what makes it extraordinary.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {FACTS.map((f) => (
              <div key={f.title} className="bg-white rounded-2xl p-6 border-l-4 border-primary shadow-sm hover:shadow-md transition-shadow">
                <f.icon className="w-7 h-7 text-primary mb-3" />
                <h3 className="font-bold text-dark mb-2">{f.title}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">{f.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── HISTORY ─── */}
      <section id="history" className="py-16 md:py-24 bg-[#0d1b2a] scroll-mt-32">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <span className="text-xs font-bold uppercase tracking-widest text-cyan-400 mb-2 block">Through the Ages</span>
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-3">A History 12,500 Years in the Making</h2>
          <p className="text-white/60 max-w-2xl mb-12 leading-relaxed">
            From retreating glaciers to tightrope walkers, the story of Niagara Falls is one of nature, daring, industry, and conservation.
          </p>
          <div className="relative pl-8 border-l-2 border-gradient-to-b from-primary to-amber-500 space-y-10">
            <div className="absolute left-0 top-0 bottom-0 w-0.5 bg-gradient-to-b from-primary to-amber-500" />
            {TIMELINE.map((t) => (
              <div key={t.year} className="relative">
                <div className="absolute -left-[2.15rem] top-1 w-4 h-4 rounded-full bg-primary border-2 border-[#0d1b2a] shadow-[0_0_0_2px_theme(colors.primary)]" />
                <span className="text-xs font-bold text-primary tracking-wider">{t.year}</span>
                <h3 className="text-white font-bold mt-1 mb-1">{t.title}</h3>
                <p className="text-sm text-white/55 leading-relaxed">{t.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── DAREDEVILS ─── */}
      <section id="daredevils" className="py-16 md:py-24 bg-gray-50 scroll-mt-32">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <span className="text-xs font-bold uppercase tracking-widest text-primary mb-2 block">Legends &amp; Stunts</span>
          <h2 className="text-3xl md:text-4xl font-bold text-dark mb-3">The Daredevils of Niagara</h2>
          <p className="text-gray-500 max-w-2xl mb-10 leading-relaxed">
            Niagara Falls has attracted thrill-seekers and showmen for over 150 years. Some found fame. Others found tragedy. All were unforgettable.
          </p>
          <div className="space-y-4">
            {DAREDEVILS.map((d) => (
              <div key={d.year} className="flex gap-4 bg-white rounded-2xl p-5 border border-gray-100 shadow-sm">
                <span className="shrink-0 bg-amber-500 text-[#031c2e] text-xs font-bold px-3 py-1.5 rounded-lg h-fit mt-0.5">
                  {d.year}
                </span>
                <div>
                  <h3 className="font-bold text-dark mb-1">{d.name}</h3>
                  <p className="text-sm text-gray-500 leading-relaxed">{d.text}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── POWER & SCIENCE ─── */}
      <section id="power" className="py-16 md:py-24 scroll-mt-32">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <span className="text-xs font-bold uppercase tracking-widest text-primary mb-2 block">Science &amp; Power</span>
          <h2 className="text-3xl md:text-4xl font-bold text-dark mb-3">The Falls That Power a Continent</h2>
          <p className="text-gray-500 max-w-3xl mb-10 leading-relaxed">
            Niagara Falls was the birthplace of modern electricity. Nikola Tesla&apos;s vision transformed not just the falls, but the entire world&apos;s relationship with power.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
              <h3 className="font-bold text-dark mb-4 pb-3 border-b border-gray-100 flex items-center gap-2">
                <Zap className="w-5 h-5 text-amber-500" /> Power Generation
              </h3>
              <ul className="space-y-3 text-sm text-gray-600">
                <li><strong className="text-dark">4–5 million kilowatts</strong> generated by both US &amp; Canadian plants</li>
                <li><strong className="text-dark">50–75%</strong> of Niagara River water is diverted for power generation</li>
                <li><strong className="text-dark">¼ of all power</strong> used in New York State and Ontario comes from Niagara</li>
                <li><strong className="text-dark">1896:</strong> World&apos;s first large-scale AC electricity transmission to Buffalo, NY</li>
                <li><strong className="text-dark">1950 Treaty</strong> regulates water diversion between US and Canada</li>
                <li>Flow is <strong className="text-dark">reduced at night</strong> under treaty to maximise generation</li>
              </ul>
            </div>
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
              <h3 className="font-bold text-dark mb-4 pb-3 border-b border-gray-100 flex items-center gap-2">
                <Mountain className="w-5 h-5 text-primary" /> Geology
              </h3>
              <ul className="space-y-3 text-sm text-gray-600">
                <li>Formed <strong className="text-dark">12,500 years ago</strong> when glaciers melted</li>
                <li>Originally located <strong className="text-dark">11 km downstream</strong> at Queenston-Lewiston</li>
                <li>Horseshoe Falls erosion: <strong className="text-dark">~30 cm/year</strong> (was 90 cm historically)</li>
                <li>Deepest section of Niagara River: <strong className="text-dark">52 metres</strong></li>
                <li>Water speed at crestline: <strong className="text-dark">up to 109 km/h (68 mph)</strong></li>
                <li>Green colour = <strong className="text-dark">60 tonnes/min</strong> dissolved salts &amp; rock flour</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* ─── TRIVIA ─── */}
      <section id="trivia" className="py-16 md:py-24 bg-gradient-to-br from-[#064a6e] to-[#0a9bb5] scroll-mt-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <span className="text-xs font-bold uppercase tracking-widest text-amber-400 mb-2 block">Did You Know?</span>
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-3">Niagara Falls Trivia</h2>
          <p className="text-white/60 max-w-2xl mb-10 leading-relaxed">
            Test your knowledge with these surprising and fascinating facts about the world&apos;s most famous waterfall.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {TRIVIA.map((t) => (
              <div key={t.q} className="bg-white/10 backdrop-blur-sm border border-white/15 rounded-2xl p-5">
                <span className="text-[10px] font-bold uppercase tracking-widest text-amber-400 block mb-2">Did You Know?</span>
                <h3 className="text-white font-bold mb-2 text-sm">{t.q}</h3>
                <p className="text-white/60 text-sm leading-relaxed">{t.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── TIPS ─── */}
      <section id="tips" className="py-16 md:py-24 bg-[#0d1b2a] scroll-mt-32">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <span className="text-xs font-bold uppercase tracking-widest text-cyan-400 mb-2 block">Travel Smart</span>
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-3">Insider Tips for Visiting</h2>
          <p className="text-white/60 max-w-2xl mb-10 leading-relaxed">
            Make the most of your Niagara Falls adventure with these essential tips from seasoned travellers.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {TIPS.map((t, i) => (
              <div key={t.title} className="bg-white/5 border border-white/10 rounded-2xl p-5">
                <span className="text-3xl font-black text-cyan-400/20 block leading-none mb-2">{String(i + 1).padStart(2, "0")}</span>
                <h3 className="text-white font-bold text-sm mb-2 flex items-center gap-2">
                  <t.icon className="w-4 h-4 text-cyan-400" /> {t.title}
                </h3>
                <p className="text-white/50 text-sm leading-relaxed">{t.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── CTA ─── */}
      <section className="py-16 md:py-24 bg-gradient-to-r from-primary to-primary-dark text-center">
        <div className="max-w-3xl mx-auto px-4">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Ready to Experience the Falls?
          </h2>
          <p className="text-white/75 mb-8 max-w-xl mx-auto">
            Browse our hand-picked tours and book with instant confirmation and free cancellation.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link href="/tours" className="inline-block bg-white text-primary font-bold px-8 py-4 rounded-full hover:bg-gray-100 transition-colors">
              Browse All Tours
            </Link>
            <Link href="/blog" className="inline-block border-2 border-white text-white font-bold px-8 py-4 rounded-full hover:bg-white/10 transition-colors">
              Read Travel Guides
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
