import simpleGit from "simple-git";
import { resolve } from "path";
import { CONFIG } from "../config.js";
import type { ImprovementTask, SiteAuditReport } from "../types.js";

const git = simpleGit(resolve(CONFIG.projectRoot));

/**
 * Create a branch, commit changes, and create a PR.
 */
export async function createPR(
  iteration: number,
  tasks: ImprovementTask[],
  beforeReport: SiteAuditReport
): Promise<string | null> {
  const branchName = `seo/iteration-${iteration}-${Date.now()}`;

  try {
    // Create and checkout branch
    await git.checkoutLocalBranch(branchName);

    // Stage changed files
    const files = [...new Set(tasks.map((t) => t.filePath))];
    for (const file of files) {
      await git.add(file);
    }

    // Build commit message
    const commitMessage = [
      `seo: iteration ${iteration} — ${tasks.length} improvements`,
      "",
      `Composite score: ${beforeReport.compositeScore}/100`,
      `Issues: ${beforeReport.totalIssues.critical} critical, ${beforeReport.totalIssues.warning} warnings`,
      "",
      "Changes:",
      ...tasks.map((t) => `- [${t.expectedImpact}] ${t.description}`),
    ].join("\n");

    await git.commit(commitMessage);
    await git.push("origin", branchName, ["--set-upstream"]);

    // Create PR via gh CLI
    const prBody = buildPRBody(iteration, tasks, beforeReport);
    const { execSync } = await import("child_process");
    const result = execSync(
      `gh pr create --title "SEO: Iteration ${iteration} — ${tasks.length} improvements" --body "${prBody.replace(/"/g, '\\"')}" --base main`,
      { cwd: resolve(CONFIG.projectRoot), encoding: "utf-8" }
    );

    const prUrl = result.trim();
    console.log(`    ✓ PR created: ${prUrl}`);

    // Switch back to main
    await git.checkout("main");

    return prUrl;
  } catch (err) {
    console.error(`    ✗ Failed to create PR: ${err instanceof Error ? err.message : err}`);
    // Try to get back to main
    try { await git.checkout("main"); } catch { /* best effort */ }
    return null;
  }
}

function buildPRBody(
  iteration: number,
  tasks: ImprovementTask[],
  report: SiteAuditReport
): string {
  return `## SEO Improvement — Iteration ${iteration}

### Before Scores
- **Composite:** ${report.compositeScore}/100
- **Critical issues:** ${report.totalIssues.critical}
- **Warnings:** ${report.totalIssues.warning}

### Changes
${tasks.map((t) => `- **[${t.expectedImpact}]** ${t.description} (\`${t.filePath}\`)`).join("\n")}

### After Scores
_Will be measured after merge and deploy._

---
Generated by seo-runner iteration ${iteration}`;
}
